### ISSUE TITLE
Unable to start on Mac OS X El Capitan

### ISSUE THREAD

**Issue by carlosromel** [MaccaTech/postgresql-mac-preferences#11]
Using last version of PostgreSQL Mac Preferences, I can install and edit Connections, but can't start installed PostgreSQL.

I can start a PostgreSQL with above command:
```
#!/bin/bash

sudo su - postgres -c '/Library/PostgreSQL/9.4/bin/pg_ctl --log /Library/PostgreSQL/9.4/log/postgres.log -D /Library/PostgreSQL/9.4/data/ start'
```

Images above show (1) command line installed (and working) and (2) configuration not working (it's indifferent to turn port or user to default value).

Thanks

![captura de tela 2015-11-09 as 03 53 56](https://cloud.githubusercontent.com/assets/420052/11026826/144e6eee-8696-11e5-867b-501c7386bd57.png)
![captura de tela 2015-11-09 as 03 54 07](https://cloud.githubusercontent.com/assets/420052/11026829/180eb070-8696-11e5-87c5-3a2b162e4f5c.png)

**Comment by mckenfra** [comment]
From your screenshot, it looks like username "_postgres" is invalid.

Did you try with username "postgres"?

**Comment by carlosromel** [comment]
Hi.

Yeap. Same problem.

TIA.

Carlos Romel
+55-11-97962-7852

carlos.romel@gmail.com
https://profiles.google.com/carlos.romel/about (principais formas de
contato)


-----BEGIN GEEK CODE BLOCK-----
Version: 3.1
GCS/CM/G/IT d-(--)@ s+++(+): a+ C+++(++++)$@ ULC(++++)$@ P(++)@ L(++)$@
E()@>$ W(++)$@ !N !o K-? w !O M(++)>+ !V PS>$ PE++(+)> Y-(+)> PGP-()>+ t(+)
!5 X(+++) !R tv? b-(++)>+++ DI(+)>++ D+()>++ G(+)>++ e(++) h(----)>---
r>+++ y(+++)
------END GEEK CODE BLOCK------
<http://profiles.friendster.com/123051496>

:wq!

2015-11-09 6:09 GMT-02:00 Francis McKenzie <notifications@github.com>:

**Comment by mckenfra** [comment]
Thanks very much for raising this, I've managed to reproduce the error. I'm working on a fix now.

**Comment by mckenfra** [comment]
I've released version 2.4.1, which I believe should fix your issue:

https://github.com/MaccaTech/postgresql-mac-preferences/releases

Could you give it a try and let me know?

Cheers, Francis

**Comment by carlosromel** [comment]
Hi.

Right now :)

Its working like charm!

Thanks for this code :)

Carlos Romel
+55-11-97962-7852

carlos.romel@gmail.com
https://profiles.google.com/carlos.romel/about (principais formas de
contato)


-----BEGIN GEEK CODE BLOCK-----
Version: 3.1
GCS/CM/G/IT d-(--)@ s+++(+): a+ C+++(++++)$@ ULC(++++)$@ P(++)@ L(++)$@
E()@>$ W(++)$@ !N !o K-? w !O M(++)>+ !V PS>$ PE++(+)> Y-(+)> PGP-()>+ t(+)
!5 X(+++) !R tv? b-(++)>+++ DI(+)>++ D+()>++ G(+)>++ e(++) h(----)>---
r>+++ y(+++)
------END GEEK CODE BLOCK------
<http://profiles.friendster.com/123051496>

:wq!

2015-11-10 15:26 GMT-02:00 Francis McKenzie <notifications@github.com>:

**Comment by mckenfra** [comment]
Ok, that's great, and thanks for taking the time to raise the issue :)
